export const products = [
  {
    id: 1,
    title: "Nokia Edge 2021",
    description: "great camera",
    price: 13500,
    img: "https://i.pinimg.com/736x/6c/19/be/6c19be2c0098d85647bbf75fe9dcf79a.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "IQOO 8 Pro 5G",
    description: "awesome look",
    price: 24500,
    img: "https://www.gizbot.com/img/2021/11/list-of-smartphones-expected-to-announce-in-november-2021-1636461291.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Samsung Galaxy S6",
    description: "longer battery life",
    price: 32700,
    img: "https://i.ytimg.com/vi/GV59RChalFg/maxresdefault.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Apple iPad Pro",
    description: "light weight & modern",
    price: 41050,
    img: "https://9to5mac.com/wp-content/uploads/sites/6/2021/04/ipad-pro-wallpaper.jpg?quality=82&strip=all",
    quantity: 1,
  },
  {
    id: 5,
    title: "Boat Headphone",
    description: "available in 3 colors",
    price: 2700,
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202110/image002_1200x768.jpeg?nkIviyDTQmKeOh1wimVl90gwb0hCdOgm&size=770:433",
    quantity: 1,
  },
  {
    id: 6,
    title: "Sony Earphones",
    description: "nice sound quality",
    price: 2100,
    img: "https://static.independent.co.uk/2022/01/19/12/Sony%20WF-1000XM4%20indybest.jpg?width=1200",
    quantity: 1,
  },
  {
    id: 7,
    title: "LG Oled TV",
    description: "eye-protective with OTT",
    price: 53070,
    img: "https://cdn.mos.cms.futurecdn.net/EM3HM3bPSaGazwdcmMPPzb.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "Panasonic Silver TV",
    description: "Good OTT experience",
    price: 51700,
    img: "https://expertreviews.b-cdn.net/sites/expertreviews/files/styles/er_main_wide/public/2021/08/panasonic_tv_model_numbers_explained_-_lead_image.jpg?itok=vcIqCsXg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Samsung S21",
    description: "advanced features",
    price: 19500,
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
];
